### ISSUE TITLE
NewsRu corpus

### ISSUE THREAD

**Issue by akutuzov** [vdobrovolskii/rucoco#13]
Hi,
You sampled texts for annotation from NewsRu.com. 
Thus, I assume  you crawled the full website and have access to its texts in some convenient format.

It would be really great if you publish this "NEwsRu corpus" in full, with as much metadata as possible. As far as I understand, there are no legal obstacles to that: all NewsRu texts are available under Creative Commons Attribution 4.0 International license.

Thanks in advance!

**Comment by vdobrovolskii** [comment]
Hi!

Thanks for your interest. [Here](https://abbyyihq-my.sharepoint.com/:u:/g/personal/vladimir_dobrovolskiy_abbyy_com/EfDkvviTivNCjWVkL7WhfeIBSnZdz0yRhssDbGOjHm2kpA?e=CiDK8x) you can find the text data that we used while building the corpus. Each file contains the text of the news article (utf8, LF) + a hyperlink to the source.

Best regards,
Vladimir

**Comment by akutuzov** [comment]
Great, thanks a lot!
